services:
  server:
    image: ghcr.io/janthoxo/gendev-scholarship:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - OFFER_CACHE_URL=${OFFER_CACHE_URL}
      - OFFER_CACHE_PASSWORD=${OFFER_CACHE_PASSWORD}
      - USER_OFFER_CACHE_URL=${USER_OFFER_CACHE_URL}
      - USER_OFFER_CACHE_PASSWORD=${USER_OFFER_CACHE_PASSWORD}
      - SERVER_PORT=3030
      - API_TIMEOUT=${API_TIMEOUT}
      - VERBYNDICH_API_KEY=${VERBYNDICH_API_KEY}
      - SERVUSSPEED_USERNAME=${SERVUSSPEED_USERNAME}
      - SERVUSSPEED_PASSWORD=${SERVUSSPEED_PASSWORD}
      - PINGPERFECT_SIGNATURE_SECRET=${PINGPERFECT_SIGNATURE_SECRET}
      - PINGPERFECT_CLIENT_ID=${PINGPERFECT_CLIENT_ID}
      - WEBWUNDER_API_KEY=${WEBWUNDER_API_KEY}
      - BYTEME_API_KEY=${BYTEME_API_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - offer-cache
      - user-offer-cache

  offer-cache:
    image: redis:8.0.1
    command: redis-server --requirepass ${OFFER_CACHE_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - offer_data:/data
    environment:
      - REDIS_PASSWORD=${OFFER_CACHE_PASSWORD}

  user-offer-cache:
    image: redis:8.0.1
    command: redis-server --requirepass ${USER_OFFER_CACHE_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - user_offer_data:/data
    environment:
      - REDIS_PASSWORD=${USER_OFFER_CACHE_PASSWORD}

volumes:
  offer_data:
    driver: local
  user_offer_data:
    driver: local
