services:
  offer-cache:
    image: redis:latest
    container_name: redis_cache
    command: redis-server --requirepass ${OFFER_CACHE_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${OFFER_CACHE_PASSWORD}

volumes:
  redis_data:
    driver: local
