services:
  server:
    image: ghcr.io/janthoxo/gendev-scholarship:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - SHARE_DB_URL=${SHARE_DB_URL}
      - SHARE_DB_NAME=${SHARE_DB_NAME}
      - SHARE_DB_USER=${SHARE_DB_USER}
      - SHARE_DB_PASSWORD=${SHARE_DB_PASSWORD}
      - OFFER_CACHE_URL=${OFFER_CACHE_URL}
      - OFFER_CACHE_PASSWORD=${OFFER_CACHE_PASSWORD}
      - USER_OFFER_CACHE_URL=${USER_OFFER_CACHE_URL}
      - USER_OFFER_CACHE_PASSWORD=${USER_OFFER_CACHE_PASSWORD}
      - SERVER_PORT=3030
      - API_TIMEOUT=${API_TIMEOUT}
      - VERBYNDICH_API_KEY=${VERBYNDICH_API_KEY}
      - SERVUSSPEED_USERNAME=${SERVUSSPEED_USERNAME}
      - SERVUSSPEED_PASSWORD=${SERVUSSPEED_PASSWORD}
      - PINGPERFECT_SIGNATURE_SECRET=${PINGPERFECT_SIGNATURE_SECRET}
      - PINGPERFECT_CLIENT_ID=${PINGPERFECT_CLIENT_ID}
      - WEBWUNDER_API_KEY=${WEBWUNDER_API_KEY}
      - BYTEME_API_KEY=${BYTEME_API_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - offer-cache
      - user-offer-cache
      - share-db

  offer-cache:
    image: redis:8.0.1
    command: redis-server --requirepass ${OFFER_CACHE_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - offer_data:/data
    environment:
      - REDIS_PASSWORD=${OFFER_CACHE_PASSWORD}

  user-offer-cache:
    image: redis:8.0.1
    command: redis-server --requirepass ${USER_OFFER_CACHE_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - user_offer_data:/data
    environment:
      - REDIS_PASSWORD=${USER_OFFER_CACHE_PASSWORD}

  share-db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${SHARE_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${SHARE_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SHARE_DB_PASSWORD}
    volumes:
      - mongodb-data:/data/db

volumes:
  offer_data:
    driver: local
  user_offer_data:
    driver: local
  mongodb-data:
