services:
  # Add this client service
  client:
    build:
      context: ../gendev-client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - API_URL=${API_URL:-http://localhost:3030}
      