name: overall docker build and push
on:
  release:
    types:
      - released
permissions:
  contents: read
  packages: write

jobs:
  server-build:
    uses: ./.github/workflows/server-package.yml

  client-build:
    uses: ./.github/workflows/client-package.yml
