name: build
on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v -o internet-provider-app .

      # - name: Run tests
      #   run: go test -v ./...
